# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ArqueoKit
                                 A QGIS plugin
 teste
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-09
        git sha              : $Format:%H$
        copyright            : (C) 2025 by s
        email                : s
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QDialog, QLabel, QComboBox, QVBoxLayout, QPushButton
from qgis.core import QgsVectorLayer, QgsProject, Qgis, QgsCoordinateReferenceSystem, QgsRasterLayer, QgsField, QgsExpression, QgsExpressionContext, QgsExpressionContextUtils, edit
from qgis.utils import iface


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .ArqueoKit_dialog import ArqueoKitDialog
import os.path


class ArqueoKit:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ArqueoKit_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&ArqueoKit')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ArqueoKit', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/ArqueoKit/icon.svg'
        self.add_action(
            icon_path,
            text=self.tr(u'Download de Camadas do IPHAN'),
            callback=self.iphandownloader,
            parent=self.iface.mainWindow())
            
        icon_path = ':/plugins/ArqueoKit/calc_area.svg'
        self.add_action(
            icon_path,
            text=self.tr(u'Calcular Área da Camada Ativa'),
            callback=self.areaCalculator,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&ArqueoKit'),
                action)
            self.iface.removeToolBarIcon(action)
            
    def loadIphanGeojsonLayer(self, link, nome_camada):
        """Carrega uma camada GeoJSON no QGIS a partir de um link WFS e define o CRS para 4674 (SIRGAS 2000)."""

        layer = QgsVectorLayer(link, nome_camada, "ogr")

        if not layer.isValid():
            self.iface.messageBar().pushMessage(
                "Erro", f"Falha ao carregar a camada: {nome_camada}", level=Qgis.Critical, duration=5
            )
            return

        # Define o CRS como EPSG:4674 (SIRGAS 2000)
        crs = QgsCoordinateReferenceSystem("EPSG:4674")
        layer.setCrs(crs)

        # Adiciona a camada ao projeto
        QgsProject.instance().addMapLayer(layer)
        
    def calculate_total_area(self, layer):
        """Calcula a área total das feições na camada de interseção e adiciona ou atualiza campos para a área usando QgsExpression."""
        provider = layer.dataProvider()

        # Adiciona os campos, se não existirem
        if layer.fields().indexFromName('area_ha') == -1:
            provider.addAttributes([QgsField("area_ha", QVariant.Double)])
        if layer.fields().indexFromName('area_m2') == -1:
            provider.addAttributes([QgsField("area_m2", QVariant.Double)])

        layer.updateFields()

        # Índice dos campos de área
        area_idx = layer.fields().indexFromName('area_ha')
        area_idx2 = layer.fields().indexFromName('area_m2')

        # Expressão para cálculo de área
        area_expression = QgsExpression("area(@geometry)")
        context = QgsExpressionContext()
        context.appendScopes(
            QgsExpressionContextUtils.globalProjectLayerScopes(layer))

        # Calcula a área total e atualiza os campos
        with edit(layer):
            for feature in layer.getFeatures():
                context.setFeature(feature)
                area = area_expression.evaluate(context)
                if area is None:
                    continue  # Pula feições com geometria inválida

                area_ha = area / 10000  # Converte para hectares
                feature.setAttribute(area_idx, area_ha)
                feature.setAttribute(area_idx2, area)
                layer.updateFeature(feature)


    def iphandownloader(self):
        """Download IPHAN layers in GeoJSON format."""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ArqueoKitDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Access checkboxes and store their values
            sitios_arq = self.dlg.sitios_arq.isChecked()
            sitios_arq_pol = self.dlg.sitios_arq_pol.isChecked()
            institut_guarda = self.dlg.institut_guarda.isChecked()
            bens_materiais = self.dlg.bens_materiais.isChecked()
            bens_imateriais = self.dlg.bens_imateriais.isChecked()
            
            if sitios_arq:
                wfs_link = "http://portal.iphan.gov.br/geoserver/SICG/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=SICG%3Asitios&maxFeatures=2147483647&outputFormat=application%2Fjson"
                self.loadIphanGeojsonLayer(wfs_link, 'Sitios_Arqueologicos_IPHAN')
                     
            if sitios_arq_pol:
                wfs_link = "http://portal.iphan.gov.br/geoserver/SICG/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=SICG%3Asitios_pol&maxFeatures=2147483647&outputFormat=application%2Fjson"
                self.loadIphanGeojsonLayer(wfs_link, 'Sitios_Arqueologicos_IPHAN')                
            
            if institut_guarda:
                wfs_link = "http://portal.iphan.gov.br/geoserver/CNA/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=CNA%3Acnigp&maxFeatures=2147483647&outputFormat=application%2Fjson"
                self.loadIphanGeojsonLayer(wfs_link, 'Instituto_Guarda_IPHAN')  
                
            if bens_materiais:
                wfs_link = "http://portal.iphan.gov.br/geoserver/SICG/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=SICG%3Atg_bem_classificacao&maxFeatures=2147483647&outputFormat=application%2Fjson"
                self.loadIphanGeojsonLayer(wfs_link, 'Bem_Material_IPHAN')  
            
            if bens_imateriais:    
                wfs_link = "http://portal.iphan.gov.br/geoserver/SICG/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=SICG%3Atg_bem_imaterial&maxFeatures=2147483647&outputFormat=application%2Fjson"
                self.loadIphanGeojsonLayer(wfs_link, 'Bem_Imaterial_IPHAN')  
                
            # Alerta o usuário que a camada foi carregada
            self.iface.messageBar().pushMessage("Processando", f"Baixando camadas no projeto", level=Qgis.Info, duration=3)
            
    def areaCalculator(self):
        """Calculate features areas of selected layer and add or update the attribute table."""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False

        result = True
        # See if OK was pressed
        if result:
            active_layer = iface.activeLayer()

            if active_layer:
                self.iface.messageBar().pushMessage("Processando", f"A camada ativa é: {active_layer.name()}", level=Qgis.Info, duration=3)
                # Executa o processo de cálculo de área
                if isinstance(active_layer, QgsVectorLayer):
                    self.calculate_total_area(active_layer)
                    print("Cálculo de áreas concluído!")
                else:
                    print("Camada ativa inválida ou não é uma camada vetorial.")

                print("Script finalizado!")
            else:
                self.iface.messageBar().pushMessage("Warning", f"No active layer!", level=Qgis.Critical, duration=10)

                
                            
           
